# Generated by Django 3.0.6 on 2020-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimagelist',
            name='uuid',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
